spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

# keycloak authentication server configurer
keycloak:
  realm: oauth2-realm
  auth-server-url: http://localhost:8090/auth
  ssl-required: external
  resource: app
  use-resource-role-mappings: true
