spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
      host: localhost
      port: 8500
  data:
    repositories:
      enabled: false
  redis:
    host: localhost
    port: 6379
    database: 0
  redis-db-2:
    host: localhost
    password:
    port: 6379
    database: 2
dubbo:
  scan:
    base-packages: com.imhui.security.provider
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost
  consumer:
    timeout: 5000
    check: false
    retries: 1
logging:
  level:
#    root: DEBUG
    com:
      imhuis:
        security: DEBUG
